#ifndef _PINNAMES_H
#define _PINNAMES_H

#include "PinNamesTypes.h"
#include "sys-gpio.h"

#ifdef __cplusplus
extern "C" {
#endif


// Specific pinmap definition
// Analog internal
#define PNAME_ANALOG_INTERNAL_BASE  0x1000
// Dual pad pin
// Direct channels are connected to analog I/Os
// (PY_C) to optimize ADC performance.
#define PDUAL                       0x2000
// Remap pin
#define PREMAP                      0x3000
// PinName mask
#define PNAME_MASK                  0xFF

typedef enum {
  // Not connected
  NC = 0xFFFFFFFF,

  // Pin name definition
  PA_0 = GPIO_PIN(PORTA, 0),
  PA_1 = GPIO_PIN(PORTA, 1),
  PA_2 = GPIO_PIN(PORTA, 2),
  PA_3 = GPIO_PIN(PORTA, 3),
  PA_4 = GPIO_PIN(PORTA, 4),
  PA_5 = GPIO_PIN(PORTA, 5),
  PA_6 = GPIO_PIN(PORTA, 6),
  PA_7 = GPIO_PIN(PORTA, 7),
  PA_8 = GPIO_PIN(PORTA, 8),
  PA_9 = GPIO_PIN(PORTA, 9),
  PA_10 = GPIO_PIN(PORTA, 10),
  PA_11 = GPIO_PIN(PORTA, 11),
  PA_12 = GPIO_PIN(PORTA, 12),
  PA_13 = GPIO_PIN(PORTA, 13),
  PA_14 = GPIO_PIN(PORTA, 14),
  PA_15 = GPIO_PIN(PORTA, 15),
  PA_16 = GPIO_PIN(PORTA, 16),
  PA_17 = GPIO_PIN(PORTA, 17),
  PA_18 = GPIO_PIN(PORTA, 18),
  PA_19 = GPIO_PIN(PORTA, 19),
  PA_20 = GPIO_PIN(PORTA, 20),
  PA_21 = GPIO_PIN(PORTA, 21),
  PA_22 = GPIO_PIN(PORTA, 22),
  PA_23 = GPIO_PIN(PORTA, 23),
  PA_24 = GPIO_PIN(PORTA, 24),
  PA_25 = GPIO_PIN(PORTA, 25),
  PA_26 = GPIO_PIN(PORTA, 26),
  PA_27 = GPIO_PIN(PORTA, 27),
  PA_28 = GPIO_PIN(PORTA, 28),
  PA_29 = GPIO_PIN(PORTA, 29),
  PA_30 = GPIO_PIN(PORTA, 30),
  PA_31 = GPIO_PIN(PORTA, 31),
#if defined PORTB
  PB_0 = GPIO_PIN(PORTB, 0),
  PB_1 = GPIO_PIN(PORTB, 1),
  PB_2 = GPIO_PIN(PORTB, 2),
  PB_3 = GPIO_PIN(PORTB, 3),
  PB_4 = GPIO_PIN(PORTB, 4),
  PB_5 = GPIO_PIN(PORTB, 5),
  PB_6 = GPIO_PIN(PORTB, 6),
  PB_7 = GPIO_PIN(PORTB, 7),
  PB_8 = GPIO_PIN(PORTB, 8),
  PB_9 = GPIO_PIN(PORTB, 9),
  PB_10 = GPIO_PIN(PORTB, 10),
  PB_11 = GPIO_PIN(PORTB, 11),
  PB_12 = GPIO_PIN(PORTB, 12),
  PB_13 = GPIO_PIN(PORTB, 13),
  PB_14 = GPIO_PIN(PORTB, 14),
  PB_15 = GPIO_PIN(PORTB, 15),
  PB_16 = GPIO_PIN(PORTB, 16),
  PB_17 = GPIO_PIN(PORTB, 17),
  PB_18 = GPIO_PIN(PORTB, 18),
  PB_19 = GPIO_PIN(PORTB, 19),
  PB_20 = GPIO_PIN(PORTB, 20),
  PB_21 = GPIO_PIN(PORTB, 21),
  PB_22 = GPIO_PIN(PORTB, 22),
  PB_23 = GPIO_PIN(PORTB, 23),
  PB_24 = GPIO_PIN(PORTB, 24),
  PB_25 = GPIO_PIN(PORTB, 25),
  PB_26 = GPIO_PIN(PORTB, 26),
  PB_27 = GPIO_PIN(PORTB, 27),
  PB_28 = GPIO_PIN(PORTB, 28),
  PB_29 = GPIO_PIN(PORTB, 29),
  PB_30 = GPIO_PIN(PORTB, 30),
  PB_31 = GPIO_PIN(PORTB, 31),
#endif  
#if defined PORTC
  PC_0 = GPIO_PIN(PORTC, 0),
  PC_1 = GPIO_PIN(PORTC, 1),
  PC_2 = GPIO_PIN(PORTC, 2),
  PC_3 = GPIO_PIN(PORTC, 3),
  PC_4 = GPIO_PIN(PORTC, 4),
  PC_5 = GPIO_PIN(PORTC, 5),
  PC_6 = GPIO_PIN(PORTC, 6),
  PC_7 = GPIO_PIN(PORTC, 7),
  PC_8 = GPIO_PIN(PORTC, 8),
  PC_9 = GPIO_PIN(PORTC, 9),
  PC_10 = GPIO_PIN(PORTC, 10),
  PC_11 = GPIO_PIN(PORTC, 11),
  PC_12 = GPIO_PIN(PORTC, 12),
  PC_13 = GPIO_PIN(PORTC, 13),
  PC_14 = GPIO_PIN(PORTC, 14),
  PC_15 = GPIO_PIN(PORTC, 15),
  PC_16 = GPIO_PIN(PORTC, 16),
  PC_17 = GPIO_PIN(PORTC, 17),
  PC_18 = GPIO_PIN(PORTC, 18),
  PC_19 = GPIO_PIN(PORTC, 19),
  PC_20 = GPIO_PIN(PORTC, 20),
  PC_21 = GPIO_PIN(PORTC, 21),
  PC_22 = GPIO_PIN(PORTC, 22),
  PC_23 = GPIO_PIN(PORTC, 23),
  PC_24 = GPIO_PIN(PORTC, 24),
  PC_25 = GPIO_PIN(PORTC, 25),
  PC_26 = GPIO_PIN(PORTC, 26),
  PC_27 = GPIO_PIN(PORTC, 27),
  PC_28 = GPIO_PIN(PORTC, 28),
  PC_29 = GPIO_PIN(PORTC, 29),
  PC_30 = GPIO_PIN(PORTC, 30),
  PC_31 = GPIO_PIN(PORTC, 31),
#endif
#if defined PORTD
  PD_0 = GPIO_PIN(PORTD, 0),
  PD_1 = GPIO_PIN(PORTD, 1),
  PD_2 = GPIO_PIN(PORTD, 2),
  PD_3 = GPIO_PIN(PORTD, 3),
  PD_4 = GPIO_PIN(PORTD, 4),
  PD_5 = GPIO_PIN(PORTD, 5),
  PD_6 = GPIO_PIN(PORTD, 6),
  PD_7 = GPIO_PIN(PORTD, 7),
  PD_8 = GPIO_PIN(PORTD, 8),
  PD_9 = GPIO_PIN(PORTD, 9),
  PD_10 = GPIO_PIN(PORTD, 10),
  PD_11 = GPIO_PIN(PORTD, 11),
  PD_12 = GPIO_PIN(PORTD, 12),
  PD_13 = GPIO_PIN(PORTD, 13),
  PD_14 = GPIO_PIN(PORTD, 14),
  PD_15 = GPIO_PIN(PORTD, 15),
  PD_16 = GPIO_PIN(PORTD, 16),
  PD_17 = GPIO_PIN(PORTD, 17),
  PD_18 = GPIO_PIN(PORTD, 18),
  PD_19 = GPIO_PIN(PORTD, 19),
  PD_20 = GPIO_PIN(PORTD, 20),
  PD_21 = GPIO_PIN(PORTD, 21),
  PD_22 = GPIO_PIN(PORTD, 22),
  PD_23 = GPIO_PIN(PORTD, 23),
  PD_24 = GPIO_PIN(PORTD, 24),
  PD_25 = GPIO_PIN(PORTD, 25),
  PD_26 = GPIO_PIN(PORTD, 26),
  PD_27 = GPIO_PIN(PORTD, 27),
  PD_28 = GPIO_PIN(PORTD, 28),
  PD_29 = GPIO_PIN(PORTD, 29),
  PD_30 = GPIO_PIN(PORTD, 30),
  PD_31 = GPIO_PIN(PORTD, 31),
#endif
#if defined PORTE
  PE_0 = GPIO_PIN(PORTE, 0),
  PE_1 = GPIO_PIN(PORTE, 1),
  PE_2 = GPIO_PIN(PORTE, 2),
  PE_3 = GPIO_PIN(PORTE, 3),
  PE_4 = GPIO_PIN(PORTE, 4),
  PE_5 = GPIO_PIN(PORTE, 5),
  PE_6 = GPIO_PIN(PORTE, 6),
  PE_7 = GPIO_PIN(PORTE, 7),
  PE_8 = GPIO_PIN(PORTE, 8),
  PE_9 = GPIO_PIN(PORTE, 9),
  PE_10 = GPIO_PIN(PORTE, 10),
  PE_11 = GPIO_PIN(PORTE, 11),
  PE_12 = GPIO_PIN(PORTE, 12),
  PE_13 = GPIO_PIN(PORTE, 13),
  PE_14 = GPIO_PIN(PORTE, 14),
  PE_15 = GPIO_PIN(PORTE, 15),
  PE_16 = GPIO_PIN(PORTE, 16),
  PE_17 = GPIO_PIN(PORTE, 17),
  PE_18 = GPIO_PIN(PORTE, 18),
  PE_19 = GPIO_PIN(PORTE, 19),
  PE_20 = GPIO_PIN(PORTE, 20),
  PE_21 = GPIO_PIN(PORTE, 21),
  PE_22 = GPIO_PIN(PORTE, 22),
  PE_23 = GPIO_PIN(PORTE, 23),
  PE_24 = GPIO_PIN(PORTE, 24),
  PE_25 = GPIO_PIN(PORTE, 25),
  PE_26 = GPIO_PIN(PORTE, 26),
  PE_27 = GPIO_PIN(PORTE, 27),
  PE_28 = GPIO_PIN(PORTE, 28),
  PE_29 = GPIO_PIN(PORTE, 29),
  PE_30 = GPIO_PIN(PORTE, 30),
  PE_31 = GPIO_PIN(PORTE, 31),
#endif
#if defined PORTF
  PF_0 = GPIO_PIN(PORTF, 0),
  PF_1 = GPIO_PIN(PORTF, 1),
  PF_2 = GPIO_PIN(PORTF, 2),
  PF_3 = GPIO_PIN(PORTF, 3),
  PF_4 = GPIO_PIN(PORTF, 4),
  PF_5 = GPIO_PIN(PORTF, 5),
  PF_6 = GPIO_PIN(PORTF, 6),
  PF_7 = GPIO_PIN(PORTF, 7),
  PF_8 = GPIO_PIN(PORTF, 8),
  PF_9 = GPIO_PIN(PORTF, 9),
  PF_10 = GPIO_PIN(PORTF, 10),
  PF_11 = GPIO_PIN(PORTF, 11),
  PF_12 = GPIO_PIN(PORTF, 12),
  PF_13 = GPIO_PIN(PORTF, 13),
  PF_14 = GPIO_PIN(PORTF, 14),
  PF_15 = GPIO_PIN(PORTF, 15),
  PF_16 = GPIO_PIN(PORTF, 16),
  PF_17 = GPIO_PIN(PORTF, 17),
  PF_18 = GPIO_PIN(PORTF, 18),
  PF_19 = GPIO_PIN(PORTF, 19),
  PF_20 = GPIO_PIN(PORTF, 20),
  PF_21 = GPIO_PIN(PORTF, 21),
  PF_22 = GPIO_PIN(PORTF, 22),
  PF_23 = GPIO_PIN(PORTF, 23),
  PF_24 = GPIO_PIN(PORTF, 24),
  PF_25 = GPIO_PIN(PORTF, 25),
  PF_26 = GPIO_PIN(PORTF, 26),
  PF_27 = GPIO_PIN(PORTF, 27),
  PF_28 = GPIO_PIN(PORTF, 28),
  PF_29 = GPIO_PIN(PORTF, 29),
  PF_30 = GPIO_PIN(PORTF, 30),
  PF_31 = GPIO_PIN(PORTF, 31),
#endif
#if defined PORTG
  PG_0 = GPIO_PIN(PORTG, 0),
  PG_1 = GPIO_PIN(PORTG, 1),
  PG_2 = GPIO_PIN(PORTG, 2),
  PG_3 = GPIO_PIN(PORTG, 3),
  PG_4 = GPIO_PIN(PORTG, 4),
  PG_5 = GPIO_PIN(PORTG, 5),
  PG_6 = GPIO_PIN(PORTG, 6),
  PG_7 = GPIO_PIN(PORTG, 7),
  PG_8 = GPIO_PIN(PORTG, 8),
  PG_9 = GPIO_PIN(PORTG, 9),
  PG_10 = GPIO_PIN(PORTG, 10),
  PG_11 = GPIO_PIN(PORTG, 11),
  PG_12 = GPIO_PIN(PORTG, 12),
  PG_13 = GPIO_PIN(PORTG, 13),
  PG_14 = GPIO_PIN(PORTG, 14),
  PG_15 = GPIO_PIN(PORTG, 15),
  PG_16 = GPIO_PIN(PORTG, 16),
  PG_17 = GPIO_PIN(PORTG, 17),
  PG_18 = GPIO_PIN(PORTG, 18),
  PG_19 = GPIO_PIN(PORTG, 19),
  PG_20 = GPIO_PIN(PORTG, 20),
  PG_21 = GPIO_PIN(PORTG, 21),
  PG_22 = GPIO_PIN(PORTG, 22),
  PG_23 = GPIO_PIN(PORTG, 23),
  PG_24 = GPIO_PIN(PORTG, 24),
  PG_25 = GPIO_PIN(PORTG, 25),
  PG_26 = GPIO_PIN(PORTG, 26),
  PG_27 = GPIO_PIN(PORTG, 27),
  PG_28 = GPIO_PIN(PORTG, 28),
  PG_29 = GPIO_PIN(PORTG, 29),
  PG_30 = GPIO_PIN(PORTG, 30),
  PG_31 = GPIO_PIN(PORTG, 31),
#endif
#if defined PORTH
  PH_0 = GPIO_PIN(PORTH, 0),
  PH_1 = GPIO_PIN(PORTH, 1),
  PH_2 = GPIO_PIN(PORTH, 2),
  PH_3 = GPIO_PIN(PORTH, 3),
  PH_4 = GPIO_PIN(PORTH, 4),
  PH_5 = GPIO_PIN(PORTH, 5),
  PH_6 = GPIO_PIN(PORTH, 6),
  PH_7 = GPIO_PIN(PORTH, 7),
  PH_8 = GPIO_PIN(PORTH, 8),
  PH_9 = GPIO_PIN(PORTH, 9),
  PH_10 = GPIO_PIN(PORTH, 10),
  PH_11 = GPIO_PIN(PORTH, 11),
  PH_12 = GPIO_PIN(PORTH, 12),
  PH_13 = GPIO_PIN(PORTH, 13),
  PH_14 = GPIO_PIN(PORTH, 14),
  PH_15 = GPIO_PIN(PORTH, 15),
  PH_16 = GPIO_PIN(PORTH, 16),
  PH_17 = GPIO_PIN(PORTH, 17),
  PH_18 = GPIO_PIN(PORTH, 18),
  PH_19 = GPIO_PIN(PORTH, 19),
  PH_20 = GPIO_PIN(PORTH, 20),
  PH_21 = GPIO_PIN(PORTH, 21),
  PH_22 = GPIO_PIN(PORTH, 22),
  PH_23 = GPIO_PIN(PORTH, 23),
  PH_24 = GPIO_PIN(PORTH, 24),
  PH_25 = GPIO_PIN(PORTH, 25),
  PH_26 = GPIO_PIN(PORTH, 26),
  PH_27 = GPIO_PIN(PORTH, 27),
  PH_28 = GPIO_PIN(PORTH, 28),
  PH_29 = GPIO_PIN(PORTH, 29),
  PH_30 = GPIO_PIN(PORTH, 30),
  PH_31 = GPIO_PIN(PORTH, 31),
#endif

  // Specific pin name
  PADC_BASE = PNAME_ANALOG_INTERNAL_BASE,
#if defined(ADC_Channel_TempSensor) 
  PADC_TEMP,
#endif
#ifdef ADC_Channel_Vrefint
  PADC_VREF,
#endif
#ifdef ADC_Channel_Vbat
  PADC_VBAT,
#endif
  ANA_START,
#ifdef SYSCFG_PMCSETR_ANA0_SEL_Pos
  ANA_0,
#endif
#ifdef SYSCFG_PMCSETR_ANA1_SEL_Pos
  ANA_1,
#endif
  // Specific pin name define in the variant
#if __has_include("PinNamesVar.h")
#include "PinNamesVar.h"
#endif
  P_END = NC
} PinName;

#ifdef __cplusplus
}
#endif

#endif
